import {Bell,Building2,ChevronDown,HeartHandshake,Home,LogOut,Menu,ShieldCheck,Truck,UtensilsCrossed,X} from 'lucide-react';import {useState} from 'react';import {NavLink,useNavigate} from 'react-router-dom';import {useTranslation} from 'react-i18next';import type {User} from '../api';
const roleLinks:Record<string,{to:string,key:string;icon:any}[]>={
 donor:[{to:'/dashboard',key:'dashboard',icon:Home},{to:'/listings',key:'listings',icon:UtensilsCrossed},{to:'/donate',key:'donate',icon:HeartHandshake},{to:'/rescues',key:'rescues',icon:Truck}],
 recipient:[{to:'/dashboard',key:'dashboard',icon:Home},{to:'/food',key:'food',icon:UtensilsCrossed},{to:'/rescues',key:'rescues',icon:HeartHandshake},{to:'/privacy',key:'privacy',icon:ShieldCheck}],
 volunteer:[{to:'/dashboard',key:'dashboard',icon:Home},{to:'/tasks',key:'tasks',icon:Truck},{to:'/rescues',key:'rescues',icon:HeartHandshake}],
 coordinator:[{to:'/dashboard',key:'dashboard',icon:Home},{to:'/reviews',key:'reviews',icon:ShieldCheck},{to:'/rescues',key:'rescues',icon:HeartHandshake},{to:'/incidents',key:'incidents',icon:Bell},{to:'/collection-points',key:'admin.collectionPoints',icon:Building2}],
 admin:[{to:'/dashboard',key:'dashboard',icon:Home},{to:'/admin',key:'admin',icon:ShieldCheck},{to:'/incidents',key:'incidents',icon:Bell},{to:'/rescues',key:'rescues',icon:HeartHandshake}]
};
export function Language(){const {i18n}=useTranslation();return <label className="language"><span className="sr-only">Language</span><select value={i18n.language} onChange={e=>i18n.changeLanguage(e.target.value)}><option value="en">English</option><option value="si">සිංහල</option><option value="ta">தமிழ்</option></select><ChevronDown size={14}/></label>}
export function Layout({user,children,onLogout}:{user:User;children:any;onLogout:()=>void}){const {t}=useTranslation();const [open,setOpen]=useState(false);const navigate=useNavigate();return <div className="app-shell">
 <header className="topbar"><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><button className="brand" onClick={()=>navigate('/dashboard')}><span className="brandmark">PB</span><span>{t('brand')}<small>{t('prototype')}</small></span></button><div className="top-actions"><Language/><button className="iconbtn" aria-label="Notifications"><Bell size={20}/><i/></button><div className="avatar">{user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div></div></header>
 <aside className={open?'sidebar open':'sidebar'}><div className="profile"><div className="avatar large">{user.name[0]}</div><div><strong>{user.name}</strong><span>{user.role} · {user.district}</span></div></div><nav>{roleLinks[user.role]?.map(({to,key,icon:Icon})=><NavLink key={to} to={to} onClick={()=>setOpen(false)}><Icon size={19}/>{t(`nav.${key}`,{defaultValue:t(key)})}</NavLink>)}</nav><button className="logout" onClick={onLogout}><LogOut size={19}/>{t('nav.logout')}</button><small className="side-note">{t('disclaimer')}</small></aside>
 <main className="main">{children}</main></div>}
