import {useEffect,useState} from 'react';import {Navigate,Route,Routes,useNavigate} from 'react-router-dom';import {api,type User} from './api';import {Layout} from './components/Layout';import {Admin,CollectionPoints,Dashboard,DonationForm,Food,Incidents,Landing,ListingDetail,Listings,Login,Privacy,RescueDetail,Rescues,Reviews,Tasks} from './pages';

export default function App(){const [user,setUser]=useState<User|null>(null);const [checking,setChecking]=useState(true);const nav=useNavigate();
 useEffect(()=>{if(!localStorage.getItem('platebridge-token')){setChecking(false);return}api<User>('/users/me').then(setUser).catch(()=>localStorage.removeItem('platebridge-token')).finally(()=>setChecking(false))},[]);
 const logout=()=>{localStorage.removeItem('platebridge-token');setUser(null);nav('/')};
 if(checking)return <div className="splash"><span className="brandmark">PB</span></div>;
 return <Routes><Route path="/" element={<Landing user={user}/>}/><Route path="/login" element={<Login onLogin={u=>{setUser(u);nav('/dashboard')}}/>}/>{user&&<Route path="/*" element={<Layout user={user} onLogout={logout}><Routes>
   <Route path="dashboard" element={<Dashboard user={user}/>}/><Route path="food" element={<Food/>}/><Route path="listings" element={<Listings/>}/><Route path="donate" element={<DonationForm/>}/><Route path="listings/:id" element={<ListingDetail user={user}/>}/><Route path="rescues" element={<Rescues user={user}/>}/><Route path="rescues/:id" element={<RescueDetail user={user}/>}/><Route path="tasks" element={<Tasks/>}/><Route path="reviews" element={<Reviews/>}/><Route path="incidents" element={<Incidents/>}/><Route path="collection-points" element={<CollectionPoints/>}/><Route path="privacy" element={<Privacy user={user} setUser={setUser}/>}/><Route path="admin" element={<Admin onReset={logout}/>}/><Route path="*" element={<Navigate to="/dashboard" replace/>}/>
 </Routes></Layout>}/>}<Route path="*" element={<Navigate to={user?'/dashboard':'/'} replace/>}/></Routes>}
